application:

  applicationName: "review-web"

  deployment:
    imagePullPolicy: Always
    image: 
      repository: docker.io/stakater/stakater-nordmart-review-ui
      tag: 1.0.22    
    env:
      PORT:
        value: "4200"
      REVIEW_API:
        # This is hardcoded!
        value: "https://review-webinar-dev.apps.preprod.jlvwjls8.kubeapp.cloud"
      PAGE_TITLE:
         valueFrom:
            secretKeyRef:
              name: review-web-review-ui-secret
              key: page_title
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200

  service:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 4200

  route:
    enabled: true

  rbac:
    serviceAccount:
      enabled: true

  forecastle:
    enabled: false

  externalSecret:
    enabled: true
    secretStore:
      name: tenant-vault-secret-store
    refreshInterval: "1m"
    files:
      review-ui-secret:
        dataFrom:
        - key: nordmart-review-ui-page-title